

(function () {
    "use strict";
    window.LUDDIES_CATALOG_SEED = [
        { id: "1", name: "cat_prod_1_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-01.webp", description: "cat_prod_1_desc", meta: "cat_prod_1_meta", price: "cat_prod_1_price", category: "science", custom: false, purchasable: 1 },
        { id: "2", name: "cat_prod_2_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-02.webp", description: "cat_prod_2_desc", meta: "cat_prod_2_meta", price: "cat_prod_2_price", category: "technology", custom: false, purchasable: 1 },
        { id: "3", name: "cat_prod_3_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-03.webp", description: "cat_prod_3_desc", meta: "cat_prod_3_meta", price: "cat_prod_3_price", category: "engineering", custom: false, purchasable: 1 },
        { id: "4", name: "cat_prod_4_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-04.webp", description: "cat_prod_4_desc", meta: "cat_prod_4_meta", price: "cat_prod_4_price", category: "mathematics", custom: false, purchasable: 1 },
        { id: "5", name: "cat_prod_5_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-05.webp", description: "cat_prod_5_desc", meta: "cat_prod_5_meta", price: "cat_prod_5_price", category: "neurodiversity", custom: false, purchasable: 1 },
        { id: "6", name: "cat_prod_6_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-06.webp", description: "cat_prod_6_desc", meta: "cat_prod_6_meta", price: "cat_prod_6_price", category: "certification mathematics", custom: false, purchasable: 1 },
        { id: "7", name: "cat_prod_7_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-07.webp", description: "cat_prod_7_desc", meta: "cat_prod_7_meta", price: "cat_prod_7_price", category: "physical", custom: false, purchasable: 1 },
        { id: "8", name: "cat_prod_8_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-08.webp", description: "cat_prod_8_desc", meta: "cat_prod_8_meta", price: "cat_prod_8_price", category: "science", custom: false, purchasable: 1 },
        { id: "9", name: "cat_prod_9_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-09.webp", description: "cat_prod_9_desc", meta: "cat_prod_9_meta", price: "cat_prod_9_price", category: "dissidents science", custom: false, purchasable: 1 },
        { id: "10", name: "cat_prod_10_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-10.webp", description: "cat_prod_10_desc", meta: "cat_prod_10_meta", price: "cat_prod_10_price", category: "dissidents technology", custom: false, purchasable: 1 },
        { id: "11", name: "cat_prod_11_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-11.webp", description: "cat_prod_11_desc", meta: "cat_prod_11_meta", price: "cat_prod_11_price", category: "dissidents neurodiversity", custom: false, purchasable: 1 },
        { id: "12", name: "cat_prod_12_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-12.webp", description: "cat_prod_12_desc", meta: "cat_prod_12_meta", price: "cat_prod_12_price", category: "neurodiversity", custom: false, purchasable: 1 },
        { id: "13", name: "cat_prod_13_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-13.webp", description: "cat_prod_13_desc", meta: "cat_prod_13_meta", price: "cat_prod_13_price", category: "science", custom: false, purchasable: 1 },
        { id: "14", name: "cat_prod_14_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-14.webp", description: "cat_prod_14_desc", meta: "cat_prod_14_meta", price: "cat_prod_14_price", category: "science", custom: false, purchasable: 1 },
        { id: "15", name: "cat_prod_15_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-15.webp", description: "cat_prod_15_desc", meta: "cat_prod_15_meta", price: "cat_prod_15_price", category: "science", custom: false, purchasable: 1 },
        { id: "16", name: "cat_prod_16_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-16.webp", description: "cat_prod_16_desc", meta: "cat_prod_16_meta", price: "cat_prod_16_price", category: "science engineering", custom: false, purchasable: 1 },
        { id: "17", name: "cat_prod_17_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-17.webp", description: "cat_prod_17_desc", meta: "cat_prod_17_meta", price: "cat_prod_17_price", category: "technology", custom: false, purchasable: 1 },
        { id: "18", name: "cat_prod_18_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-18.webp", description: "cat_prod_18_desc", meta: "cat_prod_18_meta", price: "cat_prod_18_price", category: "technology", custom: false, purchasable: 1 },
        { id: "19", name: "cat_prod_19_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-19.webp", description: "cat_prod_19_desc", meta: "cat_prod_19_meta", price: "cat_prod_19_price", category: "technology", custom: false, purchasable: 1 },
        { id: "20", name: "cat_prod_20_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-20.webp", description: "cat_prod_20_desc", meta: "cat_prod_20_meta", price: "cat_prod_20_price", category: "technology engineering", custom: false, purchasable: 1 },
        { id: "21", name: "cat_prod_21_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-21.webp", description: "cat_prod_21_desc", meta: "cat_prod_21_meta", price: "cat_prod_21_price", category: "engineering", custom: false, purchasable: 1 },
        { id: "22", name: "cat_prod_22_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-22.webp", description: "cat_prod_22_desc", meta: "cat_prod_22_meta", price: "cat_prod_22_price", category: "engineering technology", custom: false, purchasable: 1 },
        { id: "23", name: "cat_prod_23_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-23.webp", description: "cat_prod_23_desc", meta: "cat_prod_23_meta", price: "cat_prod_23_price", category: "mathematics", custom: false, purchasable: 1 },
        { id: "24", name: "cat_prod_24_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-24.webp", description: "cat_prod_24_desc", meta: "cat_prod_24_meta", price: "cat_prod_24_price", category: "mathematics engineering", custom: false, purchasable: 1 },
        { id: "25", name: "cat_prod_25_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-25.webp", description: "cat_prod_25_desc", meta: "cat_prod_25_meta", price: "cat_prod_25_price", category: "mathematics technology", custom: false, purchasable: 1 },
        { id: "26", name: "cat_prod_26_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-26.webp", description: "cat_prod_26_desc", meta: "cat_prod_26_meta", price: "cat_prod_26_price", category: "neurodiversity", custom: false, purchasable: 1 },
        { id: "27", name: "cat_prod_27_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-27.webp", description: "cat_prod_27_desc", meta: "cat_prod_27_meta", price: "cat_prod_27_price", category: "neurodiversity physical", custom: false, purchasable: 1 },
        { id: "28", name: "cat_prod_28_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-28.webp", description: "cat_prod_28_desc", meta: "cat_prod_28_meta", price: "cat_prod_28_price", category: "neurodiversity certification", custom: false, purchasable: 1 },
        { id: "29", name: "cat_prod_29_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-29.webp", description: "cat_prod_29_desc", meta: "cat_prod_29_meta", price: "cat_prod_29_price", category: "certification science", custom: false, purchasable: 1 },
        { id: "30", name: "cat_prod_30_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-30.webp", description: "cat_prod_30_desc", meta: "cat_prod_30_meta", price: "cat_prod_30_price", category: "certification", custom: false, purchasable: 1 },
        { id: "31", name: "cat_prod_31_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-31.webp", description: "cat_prod_31_desc", meta: "cat_prod_31_meta", price: "cat_prod_31_price", category: "physical science", custom: false, purchasable: 1 },
        { id: "32", name: "cat_prod_32_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-32.webp", description: "cat_prod_32_desc", meta: "cat_prod_32_meta", price: "cat_prod_32_price", category: "physical technology", custom: false, purchasable: 1 },
        { id: "33", name: "cat_prod_33_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-33.webp", description: "cat_prod_33_desc", meta: "cat_prod_33_meta", price: "cat_prod_33_price", category: "dissidents technology", custom: false, purchasable: 1 },
        { id: "34", name: "cat_prod_34_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-34.webp", description: "cat_prod_34_desc", meta: "cat_prod_34_meta", price: "cat_prod_34_price", category: "dissidents science", custom: false, purchasable: 1 },
        { id: "35", name: "cat_prod_35_title", img: "../images/luddees/identity-v2/covers/catalog-v2/catalog-cover-35.webp", description: "cat_prod_35_desc", meta: "cat_prod_35_meta", price: "cat_prod_35_price", category: "dissidents engineering neurodiversity", custom: false, purchasable: 1 }
    ];
})();
